# Generated by Django 2.2.10 on 2021-07-20 19:25

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=30, validators=[accounts.validators.allowListEmailValidator(whitelist=['gmail.com'])]),
        ),
    ]
