# Generated by Django 3.2.5 on 2021-07-21 17:42

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210721_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=30, validators=[accounts.validators.allowListEmailValidator(allowlist=['gmail.com'])]),
        ),
    ]
